spring.application.name=EcommercesAssignments
spring.datasource.url=jdbc:mysql://localhost:3306/EcommercesAssignments
spring.datasource.username=root
spring.datasource.password=Adesh@23
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
